channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - autoawq==0.2.6
      - mlflow==2.16.2
      - azureml-mlflow==1.57.0.post1
      - onnxconverter-common==1.14.0
      - onnxruntime-gpu==1.19.2