name: gpu-finetuning-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip=24.0
  - pip:
    - bitsandbytes==0.44.1
    - transformers~=4.41
    - peft~=0.13
    - accelerate~=1.0
    - trl==0.11.1
    - einops==0.8.0
    - datasets==3.0.1
    - mlflow==2.16.2
    - azureml-mlflow==1.57.0.post1
    - torchvision==0.18.0
    - torch==2.1.0
    - flash-attn==2.6.3