# yaml-language-server: $schema=ai.yaml.json

deployments:
  - name: text-embedding-ada-002
    platform: openai
    model:
      format: OpenAI
      name: text-embedding-ada-002
      version: "2"
    sku:
      name: "Standard"
      capacity: 100
  - name: raft-teacher-llama-3-1-405B-chat
    platform: serverless
    model:
      registry: azureml-meta
      name: Meta-Llama-3.1-405B-Instruct
  - name: raft-baseline-llama-2-7b-chat
    platform: serverless
    model:
      registry: azureml-meta
      name: Meta-Llama-3.1-8B-Instruct
