$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

display_name: deployment_pipeline
experiment_name: deployment_experiment
description: Pipeline to deploy a registered model
type: pipeline

inputs:
  endpoint_name:
    type: string
    default: "your-endpoint-name"
  model_name:
    type: string
    default: "your-model-name"
  compute_instance:
    type: string
    default: "Standard_E4s_v3"

jobs:
  deploy_model:
    type: command
    component: ../components/deployment/component.yml
    compute: azureml:cpu-cluster
    inputs:
      endpoint_name: ${{parent.inputs.endpoint_name}}
      model_name: ${{parent.inputs.model_name}}
      compute_instance: ${{parent.inputs.compute_instance}}