$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
name: raft_pipeline
version: 0.0.1
type: pipeline

display_name: RAFT pipeline
description: Pipeline to generate data, finetune and evaluate finetuned model

inputs:
  # Compute parameters
  instance_type:
    type: string
    optional: True
    description: Instance type to be used for validation component

  compute:
    type: string
    optional: true
    default: 'serverless'
    description: compute to run pipeline on

  # Deployment Inputs
  chat_completion_workspace_connection:
    description: workspace connection name with API details for Azure OpenAI model deployment
    type: string

  embedding_workspace_connection:
    description: workspace connection name with API details for embedding model deployment
    type: string

  # Document details
  docpath: 
    description: path to the document
    type: uri_file

  doctype:
    type: string
    description: The type of the document
    default: pdf
    enum:
      - api
      - pdf
      - json
      - txt

  # Runtime settings
  distractors:
    type: integer
    description: The number of distractor documents to include per data point or triplet
    default: 5

  chunk_size:
    type: integer
    description: The size of each chunk in number of tokens
    default: 512

  workers:
    type: integer
    description: The number of worker threads to use to generate the dataset
    default: 2

  # generate dataset settings
  questions:
    type: integer
    description: The number of data points or triplets to generate per chunk
    default: 32

  qa_threshold:
    type: integer
    description: The number of Q/A samples to generate after which to stop the generation process. Defaults to -1, which means generating Q/A samples for all documents
    default: -1

  dataset_split_ratio:
    type: number
    description: Split ratio for training and validation data
    default: 0.8

  oracle_context_percentage:
    type: number
    description: The percentage that the oracle document is included in the context
    default: 1.0

jobs:
  raft_data_preprocess:
    type: command
    component: azureml:raft_data_prep:0.0.1
    compute: '${{parent.inputs.compute}}'
    resources:
      instance_type: '${{parent.inputs.instance_type}}'
    inputs:  
      chat_completion_workspace_connection: ${{parent.inputs.chat_completion_workspace_connection}}
      embedding_workspace_connection: ${{parent.inputs.embedding_workspace_connection}}
      # Document details
      docpath: ${{parent.inputs.docpath}}
      doctype: ${{parent.inputs.doctype}}
      # Runtime settings
      distractors: ${{parent.inputs.distractors}}
      chunk_size: ${{parent.inputs.chunk_size}}
      workers: ${{parent.inputs.workers}}
      # generate dataset settings
      questions: ${{parent.inputs.questions}}
      qa_threshold: ${{parent.inputs.qa_threshold}}
      dataset_split_ratio: ${{parent.inputs.dataset_split_ratio}}
      oracle_context_percentage: ${{parent.inputs.oracle_context_percentage}}
    outputs:
      generated_dataset_full: 
        type: uri_file
        path: azureml://datastores/${{default_datastore}}/paths/azureml/${{name}}/${{output_name}}.jsonl
      generated_dataset_train: 
        type: uri_file
        path: azureml://datastores/${{default_datastore}}/paths/azureml/${{name}}/${{output_name}}.jsonl
      generated_dataset_valid:
        type: uri_file
        path: azureml://datastores/${{default_datastore}}/paths/azureml/${{name}}/${{output_name}}.jsonl
